# .github/workflows/backend-ci.yml
name: CI for Backend Services

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'services/**' # Only run if files inside any microservice directory change

jobs:
  test_ai_service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/ai-service
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Use the latest LTS version

      - name: Install Dependencies
        run: npm install

      # We don't have tests yet, but this sets up the structure.
      # The job will succeed if the install command works.
      - name: Run Tests (Placeholder)
        run: echo "No tests to run yet, but the pipeline is working!"