# .github/workflows/frontend-deploy.yml
name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main # Trigger deployment only on pushes to the main branch
  pull_request:
    types: [opened, synchronize] # Also run for PRs to generate a preview deployment
    paths:
      - 'frontend/**' # Only run this workflow if files inside the /frontend directory change

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        # This step pulls the Project ID from the .vercel directory after linking
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./frontend