# .github/workflows/supabase-migrations.yml
name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main # This will now run on EVERY push to main

jobs:
  migrate-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase Project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --non-interactive

      - name: Deploy Database Migrations
        run: supabase db push --non-interactive
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}